POST http://localhost:3000/register
Content-Type: application/json

{
  "usernaame": "mirko",
  "password": "mirko"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "usernaame": "mirko",
  "password": "mirko"
}

###

GET http://localhost:3000/protected
Authorization: Bearer //token